<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-19T00:52:59 IST" name="Suite" finished-at="2022-04-19T00:53:15 IST" duration-ms="16486">
    <groups>
    </groups>
    <test started-at="2022-04-19T00:52:59 IST" name="Test" finished-at="2022-04-19T00:53:15 IST" duration-ms="16486">
      <class name="TestNgProject.SangamAutomation.Sangam_LandingPageTest">
        <test-method is-config="true" signature="callUrl()[pri:0, instance:TestNgProject.SangamAutomation.Sangam_LandingPageTest@467f77a5]" started-at="2022-04-19T00:52:59 IST" name="callUrl" finished-at="2022-04-19T00:53:04 IST" duration-ms="4957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callUrl -->
        <test-method signature="LandingPageValidation(java.lang.String,java.lang.String)[pri:1, instance:TestNgProject.SangamAutomation.Sangam_LandingPageTest@467f77a5]" started-at="2022-04-19T00:53:04 IST" name="LandingPageValidation" data-provider="loginData" finished-at="2022-04-19T00:53:05 IST" duration-ms="990" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[yd276vijay@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[BaBaji@thulu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LandingPageValidation -->
        <test-method signature="profileValidation()[pri:2, instance:TestNgProject.SangamAutomation.Sangam_LandingPageTest@467f77a5]" started-at="2022-04-19T00:53:05 IST" name="profileValidation" finished-at="2022-04-19T00:53:15 IST" duration-ms="9793" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yadav] but found [Vijay]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yadav] but found [Vijay]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at TestNgProject.SangamAutomation.Sangam_LandingPageTest.profileValidation(Sangam_LandingPageTest.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- profileValidation -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:TestNgProject.SangamAutomation.Sangam_LandingPageTest@467f77a5]" started-at="2022-04-19T00:53:15 IST" name="closeDriver" finished-at="2022-04-19T00:53:15 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- TestNgProject.SangamAutomation.Sangam_LandingPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
